import { CHAT_AGENT_TOOLS } from "@/lib/buzz/agent-chat-tools";

// The MCP tool surface, as a list of names.
//
// It exists so /api/agent/manifest can tell an agent "the surface changed"
// without the agent having to authenticate, connect and diff a tools/list.
// The definitions themselves stay in src/app/api/[transport]/route.ts —
// a Next route file may only export HTTP handlers, so the names cannot be
// exported from where they are declared.
//
// That split is the risk, and it is the exact failure the /start document
// exists to avoid: the propose_screen tool describes its panels in a
// hardcoded string and that string drifted from PROJECT_WIDGETS. So this
// list is not trusted to stay correct by good intentions —
// tests/agent-manifest.test.ts parses the route file and fails when the two
// disagree. Add a tool, add it here, or CI says so.
//
// Deprecated aliases are deliberately absent: they are the old names for
// tools already listed, and an agent discovering them would be learning a
// vocabulary we are trying to retire.
export const CORE_MCP_TOOL_NAMES: string[] = [
  "whoami",
  "list_wake_inbox",
  "heartbeat",
  "emit_run_event",
  "propose_screen",
  "propose_panel",
  "brief",
  "my_fleet",
  "provision_agent",
  "find_decisions",
  "read_plan",
  "ask_question",
  "add_option",
  "add_evidence",
  "decide",
  "record_expectation",
  "retract_plan_node",
  "set_focus",
  "acknowledge_wake",
  "get_tree",
  "create_space",
  "create_project",
  "rename_project",
  "delete_project",
  "reorder_projects",
  "create_list",
  "rename_list",
  "update_list_meta",
  "update_project_meta",
  "delete_list",
  "reorder_lists",
  "move_list",
  "list_statuses",
  "create_status",
  "create_custom_field",
  "list_milestones",
  "create_milestone",
  "update_milestone",
  "delete_milestone",
  "set_task_milestone",
  "list_tasks",
  "get_task",
  "list_context_packets",
  "get_context_packet",
  "create_context_packet",
  "update_context_packet",
  "acknowledge_task_context",
  "attach_context_packet",
  "detach_context_packet",
  "delete_context_packet",
  "list_decisions_for_task",
  "create_decision",
  "supersede_decision",
  "assess_decision_impact",
  "create_task",
  "create_tasks",
  "reorder_tasks",
  "update_task",
  "set_estimate",
  "complete_task",
  "request_approval",
  "delete_task",
  "claim_task",
  "release_task",
  "set_checklist",
  "add_dependency",
  "remove_dependency",
  "search_tasks",
  "semantic_search",
  "list_comments",
  "add_comment",
  "list_my_mentions",
  "mark_mention_read",
  "list_members",
  "create_sprint",
  "list_sprints",
  "list_sprint_templates",
  "apply_sprint_template",
  "update_sprint",
  "sprint_summary",
  "set_sprint_capacity",
  "set_sprint_retrospective",
  "get_sprint_board",
  "get_sprint_planning",
  "get_execution_policy",
  "create_execution_plan",
  "revise_execution_plan_context",
  "list_execution_plans",
  "get_execution_plan",
  "get_outcome_assurance",
  "submit_outcome_evidence",
  "review_outcome_criterion",
  "get_execution_readiness",
  "get_execution_control",
  "reconcile_execution_plan",
  "dispatch_execution_wave",
  "get_roadmaps",
  "create_roadmap",
  "add_roadmap_phase",
  "update_roadmap_phase",
  "remove_roadmap_phase",
  "assign_project_to_phase",
  "assign_list_to_phase",
  "create_scheduled_task",
  "list_scheduled_tasks",
  "set_scheduled_task_enabled",
  "delete_scheduled_task",
  "list_events",
  "register_webhook",
  "list_webhooks",
  "delete_webhook",
  "list_skills",
  "get_skill",
  "create_skill",
  "list_blueprints",
  "create_blueprint",
  "instantiate_blueprint",
  "list_docs",
  "get_doc",
  "create_doc",
  "update_doc",
  "next_task",
  "handoff_task",
  "start_run",
  "finish_run",
  "report_error",
  "list_channels",
  "create_channel",
  "read_channel",
  "mark_channel_read",
  "set_channel_topic",
  "list_reference_targets",
  "log_time",
  "list_time_entries",
  "list_goals",
  "create_goal",
  "set_goal_progress",
  "list_automations",
  "create_automation",
  "delete_automation",
  "list_templates",
  "get_template",
  "apply_template",
  "list_starter_templates",
  "apply_starter_template",
  "list_custom_fields",
  "get_task_fields",
  "set_task_field",
  "clear_task_field",
  "list_checklist_templates",
  "apply_checklist_template",
  "create_checklist_template",
  "get_portfolio",
  "get_task_network",
  "update_comment",
  "delete_comment",
  "resolve_comment",
  "get_wallet",
  "buy_credits",
  "settle_payment",
  "list_open_revisions",
  "address_revision",
  "request_revision",
  "get_project_updates",
  "list_project_docs",
  "write_project_doc",
  "list_pages",
  "pin_page",
  "read_page",
  "write_page",
];

// Chat's tools carry their own definitions in a lib module, so they can be
// read live rather than transcribed. Nothing to keep in sync here.
export const MCP_TOOL_NAMES: string[] = [
  ...CORE_MCP_TOOL_NAMES,
  ...CHAT_AGENT_TOOLS.map((tool) => tool.name),
];
