import { ConvexError, v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { requireIdentity } from "./_authz";
import { sha256Hex } from "./_agentAuth";
import { assertCanCreateAgent } from "./_adminEntitlements";
import { normalizeCapabilities } from "./capabilities";
import {
  CODE_LOOKUP_RULE,
  DEVICE_REQUEST_RULE,
  consumeRateLimit,
} from "./_rateLimit";
import { emitEvent } from "./events";

// OAuth 2.0 Device Authorization Grant (RFC 8628) for agent runtimes.
//
// The problem this replaces: sign in, create an agent, copy a `cua_…` key,
// paste it into a config. That key travels through a chat transcript, a
// clipboard, and usually a file that gets committed — a key that has been in
// a conversation has been in a log. And consent is uninformed, because you
// mint the key first and decide what the agent may do afterwards, on a
// different screen, having already stopped paying attention.
//
// Here the agent asks for a code, prints it, and a human types it at /link.
// The consent screen names the blast radius — which scope, which role, which
// lists, how many actions a day — using the governance fields the schema
// already has. The key is minted when the poller collects it and returned
// exactly once.
//
// No secret is generated here: Convex mutations have no CSPRNG, so the
// device code and the API key are both generated by the Next.js route with
// node:crypto and arrive already-made, exactly as oauth.ts does for
// authorization codes. Only hashes are stored.

const DEVICE_CODE_TTL_MS = 10 * 60 * 1000;
const DEFAULT_POLL_INTERVAL_SEC = 5;
// RFC 8628 §3.5: each slow_down bumps the interval the client must respect.
const SLOW_DOWN_STEP_SEC = 5;
const MAX_POLL_INTERVAL_SEC = 30;

// No 0/O, 1/I/L, 2/Z, 5/S, 8/B — a human reads this off one screen and types
// it into another, and every one of those pairs is a support ticket.
export const DEVICE_CODE_ALPHABET = "ACDEFGHJKMNPQRTUVWXY3479";

export function isWellFormedUserCode(code: string): boolean {
  return /^[ACDEFGHJKMNPQRTUVWXY3479]{4}-[ACDEFGHJKMNPQRTUVWXY3479]{4}$/.test(
    code,
  );
}

// A user code is typed by a person, so accept the shapes a person produces:
// lower case, missing dash, surrounding space. Anything else is not repaired.
export function normalizeUserCode(input: string): string {
  const bare = input.trim().toUpperCase().replace(/[\s-]/g, "");
  return bare.length === 8 ? `${bare.slice(0, 4)}-${bare.slice(4)}` : bare;
}

// Which bucket a device-code request counts against.
//
// `createDeviceRequest` has to be public and unauthenticated — the caller is
// a machine with no credential, which is the entire point of the grant — so
// anyone can call it directly and pass whatever `clientIp` they like. A
// per-IP limit that trusts an attacker-supplied IP is not a limit.
//
// So the route proves it is the route with a shared secret:
//
//   - Secret configured AND matches → trust clientIp, per-IP budgets.
//   - Secret configured AND doesn't → every such caller shares ONE bucket,
//     which makes direct flooding cost the flooder rather than the table.
//   - Secret not configured at all → trust clientIp. Fail-open, deliberately:
//     the alternative collapses every real user of an existing deployment
//     into a single shared budget the moment they upgrade, and what is at
//     stake here is storage growth, not an authorization boundary. Setting
//     DEVICE_PROXY_SECRET on both Next and Convex is the hardened posture.
function deviceRateSubject(clientIp?: string, proxySecret?: string): string {
  const expected = process.env.DEVICE_PROXY_SECRET;
  if (expected && proxySecret !== expected) return "unverified";
  return clientIp && clientIp.length <= 64 ? clientIp : "unknown";
}

export type DeviceRequestState =
  | "pending"
  | "approved"
  | "denied"
  | "claimed"
  | "expired"
  | "not_found";

async function byDeviceCode(ctx: QueryCtx | MutationCtx, deviceCode: string) {
  return await ctx.db
    .query("agentAuthRequests")
    .withIndex("by_device_hash", (q) =>
      q.eq("deviceCodeHash", sha256Hex(deviceCode)),
    )
    .unique();
}

// ── The agent's side ───────────────────────────────────────────────────

// Called by POST /oauth/device. Public and unauthenticated by design: the
// caller is a machine that has no credential yet, which is the entire point
// of the grant. It cannot learn anything — the row it creates is inert until
// a signed-in human approves it.
export const createDeviceRequest = mutation({
  args: {
    deviceCode: v.string(),
    userCode: v.string(),
    clientName: v.string(),
    // Read from request headers by /oauth/device — Convex cannot see the
    // caller's address itself.
    clientIp: v.optional(v.string()),
    // Proves the caller really is our own route rather than someone driving
    // this public mutation directly with a spoofed clientIp. See
    // deviceRateSubject for what happens when it doesn't check out.
    proxySecret: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await consumeRateLimit(
      ctx,
      DEVICE_REQUEST_RULE,
      deviceRateSubject(args.clientIp, args.proxySecret),
      "Too many connection attempts. Wait a few minutes and try again.",
    );
    if (!isWellFormedUserCode(args.userCode)) {
      throw new ConvexError("Malformed user code");
    }
    // A live collision would send a human's approval to the wrong agent.
    const clash = await ctx.db
      .query("agentAuthRequests")
      .withIndex("by_user_code", (q) => q.eq("userCode", args.userCode))
      .collect();
    const now = Date.now();
    if (clash.some((row) => row.expiresAt > now && row.status !== "claimed")) {
      throw new ConvexError("User code collision, retry");
    }
    const clientName = args.clientName.trim().slice(0, 60) || "an agent";
    await ctx.db.insert("agentAuthRequests", {
      deviceCodeHash: sha256Hex(args.deviceCode),
      userCode: args.userCode,
      clientName,
      status: "pending",
      pollIntervalSec: DEFAULT_POLL_INTERVAL_SEC,
      expiresAt: now + DEVICE_CODE_TTL_MS,
      createdAt: now,
    });
    return {
      expiresIn: DEVICE_CODE_TTL_MS / 1000,
      interval: DEFAULT_POLL_INTERVAL_SEC,
    };
  },
});

// Called by POST /oauth/token with the device_code grant. Returns the state
// the route turns into an RFC error code, plus — once and only once — the
// agent the key should be minted against.
//
// The key itself is minted by the caller: it arrives here as a hash, so the
// plaintext never exists in the database at any point, not even for the ten
// minutes between approval and collection.
export const claimDeviceRequest = mutation({
  args: {
    deviceCode: v.string(),
    keyHash: v.optional(v.string()),
    keyPrefix: v.optional(v.string()),
  },
  handler: async (
    ctx,
    args,
  ): Promise<{
    state: DeviceRequestState;
    slowDown?: boolean;
    interval?: number;
    agentId?: Id<"agents">;
    agentName?: string;
    agentCreated?: boolean;
    scopeName?: string;
  }> => {
    const row = await byDeviceCode(ctx, args.deviceCode);
    // An unknown device code and an expired one are the same answer to the
    // caller; distinguishing them would let someone probe for live codes.
    if (!row) return { state: "not_found" };
    const now = Date.now();
    if (row.expiresAt <= now && row.status !== "claimed") {
      return { state: "expired" };
    }

    if (row.status === "pending") {
      // Rate limiting. A poller that comes back faster than the interval it
      // was given is told to slow down, and the interval it must respect
      // grows — otherwise "slow_down" is advice rather than a limit.
      const early =
        row.lastPolledAt !== undefined &&
        now - row.lastPolledAt < row.pollIntervalSec * 1000;
      const interval = early
        ? Math.min(row.pollIntervalSec + SLOW_DOWN_STEP_SEC, MAX_POLL_INTERVAL_SEC)
        : row.pollIntervalSec;
      await ctx.db.patch(row._id, {
        lastPolledAt: now,
        pollIntervalSec: interval,
      });
      return { state: "pending", slowDown: early, interval };
    }
    if (row.status === "denied") return { state: "denied" };
    // Terminal. A replayed device code gets invalid_grant rather than a
    // second key: this is the whole reason the row survives collection.
    if (row.status === "claimed") return { state: "claimed" };

    // Approved and not yet collected. The one path that issues a key.
    if (!row.agentId) return { state: "denied" };
    const agent = await ctx.db.get(row.agentId);
    // The human can pause or delete the agent between approving and the
    // poller arriving. Re-check rather than trusting the approval.
    if (!agent || agent.status !== "active") return { state: "denied" };
    if (!args.keyHash || !args.keyPrefix) {
      throw new ConvexError("Key material is required to claim");
    }
    await ctx.db.insert("agentKeys", {
      agentId: agent._id,
      keyHash: args.keyHash,
      keyPrefix: args.keyPrefix,
      createdAt: now,
    });
    await ctx.db.patch(row._id, { status: "claimed" });

    // Approval and collection are separate events because they are separate
    // facts: a human said yes at one time, and a key came into existence at
    // another. An approval never collected is worth being able to see.
    await emitEvent(ctx, {
      scopeType: agent.parentType,
      scopeId: agent.parentId,
      type: "agent.key_issued",
      actor: { type: "system", id: "device_flow", name: "Device authorization" },
      entityType: "agent",
      entityId: agent._id,
      entityTitle: agent.name,
      payload: {
        client: row.clientName,
        keyPrefix: args.keyPrefix,
        approvedBy: row.approvedByClerkId ?? null,
        grant: "device_code",
      },
    });
    return {
      state: "approved",
      agentId: agent._id,
      agentName: agent.name,
      agentCreated: row.agentCreated ?? false,
      scopeName: await scopeNameFor(ctx, agent),
    };
  },
});

async function scopeNameFor(ctx: QueryCtx | MutationCtx, agent: Doc<"agents">) {
  if (agent.parentType === "user") return "your personal space";
  const workspace = await ctx.db.get(agent.parentId as Id<"workspaces">);
  return workspace?.name ?? "a workspace";
}

// ── The human's side ───────────────────────────────────────────────────

// What /link shows after the code is entered: who is asking, and every scope
// and agent this particular human could point them at. Deliberately returns
// a status rather than throwing on a bad code — "that code has expired" is a
// thing the screen has to be able to say.
//
// A MUTATION, though it reads. That is not an accident and it is not
// convenience: a lookup that must be counted is a write.
//
// Unthrottled, this is an enumeration oracle with a serious payoff. Anybody
// with an account could sweep the user-code space, and a hit lets them call
// approveDeviceRequest binding THEIR agent in THEIR workspace to somebody
// else's pending device code — so the victim's runtime connects, with a
// valid key, to an attacker-controlled workspace and starts taking
// instructions from it. Nothing looks wrong from either side.
//
// Only FAILED lookups are counted. Somebody connecting an agent gets the
// code right, so a legitimate user never approaches the ceiling no matter
// how many agents they connect; an enumerator produces almost nothing but
// failures. Counting successes too would rate-limit exactly the wrong people.
export const lookupUserCode = mutation({
  args: { userCode: v.string() },
  handler: async (ctx, { userCode }) => {
    const identity = await requireIdentity(ctx);
    const miss = async (state: "not_found" | "expired") => {
      await consumeRateLimit(
        ctx,
        CODE_LOOKUP_RULE,
        identity.subject,
        "Too many incorrect codes. Wait a few minutes and try again.",
      );
      return { state } as const;
    };

    const code = normalizeUserCode(userCode);
    if (!isWellFormedUserCode(code)) return await miss("not_found");
    const rows = await ctx.db
      .query("agentAuthRequests")
      .withIndex("by_user_code", (q) => q.eq("userCode", code))
      .collect();
    const now = Date.now();
    const row =
      rows.find((r) => r.status === "pending" && r.expiresAt > now) ??
      rows.sort((a, b) => b.createdAt - a.createdAt)[0];
    if (!row) return await miss("not_found");
    // A settled request is a real answer about a real code, so it is not a
    // miss — but it is also not a hit worth spending somebody's budget on.
    if (row.status !== "pending") {
      return { state: row.status };
    }
    if (row.expiresAt <= now) return await miss("expired");

    // Every place this human could put an agent, and the agents already
    // there. Offering existing agents matters: reconnecting a runtime you
    // already governed must not silently create a second principal that
    // inherits none of that governance.
    const memberships = await ctx.db
      .query("memberships")
      .withIndex("by_user", (q) => q.eq("userClerkId", identity.subject))
      .collect();
    const workspaces = (
      await Promise.all(
        memberships.map(async (membership) => {
          const workspace = await ctx.db.get(membership.workspaceId);
          return workspace
            ? {
                membership,
                workspace,
              }
            : null;
        }),
      )
    ).filter((entry) => entry !== null);

    const scopes = [
      {
        parentType: "user" as const,
        parentId: identity.subject,
        name: "Personal space",
        // Personal agents are self-managed; there is no role that can
        // withhold this from you in your own space.
        canManage: true,
      },
      ...workspaces.map(({ membership, workspace }) => ({
        parentType: "workspace" as const,
        parentId: workspace._id as string,
        name: workspace.name,
        canManage:
          membership.role === "owner" || membership.role === "admin",
      })),
    ];

    const agentsByScope = await Promise.all(
      scopes.map(async (scope) => {
        const agents = await ctx.db
          .query("agents")
          .withIndex("by_parent", (q) =>
            q.eq("parentType", scope.parentType).eq("parentId", scope.parentId),
          )
          .collect();
        return agents
          .filter((agent) => agent.status === "active")
          .map((agent) => ({
            agentId: agent._id,
            name: agent.name,
            scopeId: scope.parentId,
            role: agent.role ?? ("member" as const),
            lastSeenAt: agent.lastSeenAt ?? null,
          }));
      }),
    );

    return {
      state: "pending" as const,
      clientName: row.clientName,
      expiresAt: row.expiresAt,
      scopes,
      agents: agentsByScope.flat(),
    };
  },
});

// Approval. This is where consent becomes governance: the four fields the
// screen asked about are written onto the agent in the same transaction that
// authorizes the request, so there is no window in which a connected agent
// has broader powers than the human agreed to.
export const approveDeviceRequest = mutation({
  args: {
    userCode: v.string(),
    // Either bind to an agent that exists…
    agentId: v.optional(v.id("agents")),
    // …or create one in this scope.
    parentType: v.optional(v.union(v.literal("user"), v.literal("workspace"))),
    parentId: v.optional(v.string()),
    agentName: v.optional(v.string()),
    capabilities: v.optional(v.array(v.string())),
    // Governance, asked at the moment of consent rather than afterwards.
    role: v.union(v.literal("member"), v.literal("readonly")),
    allowedListIds: v.optional(v.array(v.id("lists"))),
    dailyActionLimit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const identity = await requireIdentity(ctx);
    const code = normalizeUserCode(args.userCode);
    const rows = await ctx.db
      .query("agentAuthRequests")
      .withIndex("by_user_code", (q) => q.eq("userCode", code))
      .collect();
    const now = Date.now();
    const row = rows.find((r) => r.status === "pending" && r.expiresAt > now);
    if (!row) {
      // Counted for the same reason lookupUserCode is: skipping the lookup
      // and guessing straight at approve would otherwise be an unthrottled
      // path to the same oracle, and this one binds an agent on a hit.
      //
      // RETURNED, not thrown — and that distinction is the whole guard.
      // A Convex mutation that throws rolls its transaction back, which
      // discards the counter increment along with it, so a rate limit that
      // counts and then throws in the same mutation counts nothing at all.
      // The first version of this did exactly that and the test below
      // caught it. Genuine authorization failures still throw, because
      // those SHOULD roll back.
      await consumeRateLimit(
        ctx,
        CODE_LOOKUP_RULE,
        identity.subject,
        "Too many incorrect codes. Wait a few minutes and try again.",
      );
      return { approved: false as const, reason: "invalid_code" as const };
    }

    let agentId: Id<"agents">;
    let agentCreated = false;
    if (args.agentId) {
      const agent = await ctx.db.get(args.agentId);
      if (!agent || agent.status !== "active") {
        throw new ConvexError("That agent is not available");
      }
      await requireManage(ctx, agent.parentType, agent.parentId, identity.subject);
      agentId = agent._id;
    } else {
      if (!args.parentType || !args.parentId || !args.agentName?.trim()) {
        throw new ConvexError("A scope and a name are required for a new agent");
      }
      await requireManage(ctx, args.parentType, args.parentId, identity.subject);
      await assertCanCreateAgent(ctx, args.parentType, args.parentId);
      const capabilities = normalizeCapabilities(
        args.capabilities,
        "capabilities",
      );
      agentId = await ctx.db.insert("agents", {
        name: args.agentName.trim().slice(0, 80),
        // The client's self-reported name is the most useful thing anybody
        // will read on the Agents page six weeks from now.
        description: `Connected from ${row.clientName}`,
        capabilities: capabilities.length > 0 ? capabilities : undefined,
        parentType: args.parentType,
        parentId: args.parentId,
        status: "active",
        createdByClerkId: identity.subject,
        createdAt: now,
      });
      agentCreated = true;
    }

    // Governance is applied to new and existing agents alike. Approving a
    // narrower scope for an agent that already had a wider one is a real
    // instruction, not a no-op.
    await ctx.db.patch(agentId, {
      role: args.role,
      allowedListIds:
        args.allowedListIds && args.allowedListIds.length > 0
          ? args.allowedListIds
          : undefined,
      dailyActionLimit: args.dailyActionLimit,
    });

    await ctx.db.patch(row._id, {
      status: "approved",
      approvedByClerkId: identity.subject,
      agentId,
      agentCreated,
    });

    // A credential grant must never be invisible. This is the moment a human
    // hands a machine the ability to act as them, so it goes in the activity
    // log with the full blast radius attached — not just "an agent appeared".
    // It also fans out to webhooks, which is how a security team finds out.
    const agent = (await ctx.db.get(agentId))!;
    await emitEvent(ctx, {
      scopeType: agent.parentType,
      scopeId: agent.parentId,
      type: "agent.authorized",
      actor: {
        type: "user",
        id: identity.subject,
        name: identity.subject,
      },
      entityType: "agent",
      entityId: agentId,
      entityTitle: agent.name,
      payload: {
        client: row.clientName,
        agentCreated,
        role: args.role,
        dailyActionLimit: args.dailyActionLimit ?? null,
        restrictedToLists: args.allowedListIds?.length ?? 0,
        grant: "device_code",
      },
    });
    return { approved: true as const, agentId, agentCreated };
  },
});

export const denyDeviceRequest = mutation({
  args: { userCode: v.string() },
  handler: async (ctx, { userCode }) => {
    await requireIdentity(ctx);
    const code = normalizeUserCode(userCode);
    const rows = await ctx.db
      .query("agentAuthRequests")
      .withIndex("by_user_code", (q) => q.eq("userCode", code))
      .collect();
    const now = Date.now();
    const row = rows.find((r) => r.status === "pending" && r.expiresAt > now);
    if (row) await ctx.db.patch(row._id, { status: "denied" });
    return { denied: true };
  },
});

// Same bar agents.ts applies to minting a key by hand: personal agents are
// self-managed, workspace agents need owner or admin. Connecting an agent is
// exactly as consequential as creating one, so it cannot be the softer path.
async function requireManage(
  ctx: MutationCtx,
  parentType: "user" | "workspace",
  parentId: string,
  subject: string,
) {
  if (parentType === "user") {
    if (parentId !== subject) throw new ConvexError("Forbidden");
    return;
  }
  const membership = await ctx.db
    .query("memberships")
    .withIndex("by_user_and_workspace", (q) =>
      q.eq("userClerkId", subject).eq("workspaceId", parentId as Id<"workspaces">),
    )
    .unique();
  if (!membership) throw new ConvexError("Forbidden");
  if (membership.role !== "owner" && membership.role !== "admin") {
    throw new ConvexError(
      "Only workspace owners and admins can connect an agent",
    );
  }
}
