[package]
name = "operate-desktop"
version = "0.1.0"
edition = "2021"
description = "operate.to desktop shell"
license = "UNLICENSED"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-updater = "2"

[features]
default = []
